### ISSUE TITLE
Fix Test to showDiagnostics() printout

### ISSUE THREAD

**Issue by mariannegoldin** [intricatus/csc142_HW2#4]
Test is now currently showing errors, however, it is not printing out showDiagnostics.

Fix it and /or other files to enable this printout.

**Comment by jlrestad** [comment]
I changed the method calls to the variable, ex. sd1.MERCURY, instead of SunDistance.MERCURY.
Added the print call statement to showDiagnostics.

**Comment by mariannegoldin** [comment]
Thank you! 

I was playing around with the object names between the static calling version, SunDistance and the dynamic calling version, sd1.

The crux was in using the sysout print to print the showDiagnostics(). Good catch!
