### ISSUE TITLE
Fix Astronauts lbs conversion

### ISSUE THREAD

**Issue by mariannegoldin** [intricatus/csc142_HW2#8]
public double getPlanetaryWeight() {
    	double mass = ((identity.getWeight() * TO_NEWTONS ) / EARTH_GRAVITY) / TO_NEWTONS; 
    	return mass * planet.getFreeFall();
    }

Need to evaluate this , currently seems like TO_NEWTONS is being cancelled out
Should the last conversion be * TO_LBS?

**Comment by intricatus** [comment]
It was already in pounds, so we just need to multiply by the ration of earth acceleration over the acceleration of the planet we want. The change I pushed should have solved this.

**Comment by intricatus** [comment]
It is in test3 for now. Let's close it once we merge.
