### ISSUE TITLE
SpaceCraft: Consistent printout of Person and Astronaut 

### ISSUE THREAD

**Issue by mariannegoldin** [intricatus/csc142_HW2#9]
There are issues printing these calls out together, ensure that both can be called in same class and printing out correctly.

**Comment by intricatus** [comment]
In test3 the output looks consistent to me. Is there anything specifically wrong that you see?

**Comment by mariannegoldin** [comment]
Fixed by merge pull request #10

**Comment by mariannegoldin** [comment]
Agreed, test3 branch output was consistent. I cleaned up that branch and
pulled it into master.

Barring any cleanup of master, I think we are at done.
